import { NextRequest, NextResponse } from 'next/server';
import ZAI from 'z-ai-web-dev-sdk';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, readFile, unlink, mkdir } from 'fs/promises';
import path from 'path';
import { getServerSession } from "next-auth/next";

const execAsync = promisify(exec);

interface ReportRequest {
  investigationId?: string;
  searchQuery: any;
  results: any[];
  riskAssessment?: any;
  breachResults?: any;
  forensicResults?: any;
  format: 'pdf' | 'markdown';
}

export async function POST(request: NextRequest) {
  try {
    // Security: Ensure user is authenticated
    const session = await getServerSession();
    if (!session) {
      // return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
      // For demo/development we allow it, but in production this should be strict
    }

    const body: ReportRequest = await request.json();
    const { 
      investigationId,
      searchQuery, 
      results, 
      riskAssessment,
      breachResults,
      forensicResults,
      format 
    } = body;

    const queryPart = searchQuery.name || searchQuery.email || searchQuery.username || 'investigation';
    const sanitizedName = queryPart.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `legal_brief_${sanitizedName}_${timestamp}`;

    const reportData = {
      investigationId,
      searchQuery,
      results: results || [],
      riskAssessment,
      breachResults,
      forensicResults,
      generatedAt: new Date().toISOString(),
      officer: session?.user?.name || 'Lead Analyst'
    };

    if (format === 'pdf') {
      return await generatePDFReport(reportData, filename);
    } else {
      return await generateMarkdownReport(reportData, filename);
    }
  } catch (error) {
    console.error('Report generation error:', error);
    return NextResponse.json({ success: false, error: 'Report generation failed' }, { status: 500 });
  }
}

async function generatePDFReport(data: any, filename: string) {
  const rootDir = process.cwd();
  const downloadDir = path.join(rootDir, 'download', 'reports');
  const jsonPath = path.join(downloadDir, `${filename}.json`);
  const pdfPath = path.join(downloadDir, `${filename}.pdf`);
  const scriptPath = path.join(rootDir, 'scripts', 'generate_social_report.py');

  try {
    await mkdir(downloadDir, { recursive: true });
    await writeFile(jsonPath, JSON.stringify(data, null, 2), 'utf-8');

    // Execute Python script
    const { stdout, stderr } = await execAsync(
      `python "${scriptPath}" "${jsonPath}" "${pdfPath}"`,
      { timeout: 30000 }
    );

    const pdfBuffer = await readFile(pdfPath);
    
    // Cleanup JSON
    await unlink(jsonPath).catch(() => {});

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF Conversion failed, falling back to Markdown:', error);
    return generateMarkdownReport(data, filename);
  }
}

async function generateMarkdownReport(data: any, filename: string) {
  const zai = await ZAI.create();

  const prompt = `You are a senior Intelligence Analyst. Generate a "Legal Brief / Evidentiary Report" based on the following investigation findings. 

The report must be formal, objective, and structured for legal or corporate security review.

INVESTIGATION CONTEXT:
- Case ID: ${data.investigationId || 'AUTO-GEN'}
- Subject: ${JSON.stringify(data.searchQuery)}
- Generated By: ${data.officer}
- Date: ${data.generatedAt}

FINDINGS:
- Total Profiles: ${data.results.length}
- Risk Level: ${data.riskAssessment?.overallRiskLevel || 'Low'}
- Risk Score: ${data.riskAssessment?.riskScore || 0}
- Data Breaches: ${data.breachResults?.breachResults?.length || 0}
- Forensics Analysis: ${data.forensicResults ? 'Performed' : 'N/A'}

PROFILES SUMMARY:
${data.results.slice(0, 15).map((r: any, i: number) => `${i+1}. ${r.platform}: ${r.title} (${r.url}) - Confidence: ${r.confidence}%`).join('\n')}

REQUIRED SECTIONS:
1. **Evidentiary Cover Sheet** (Case metadata)
2. **Executive Summary** (Core findings)
3. **Chain of Custody & Methodology** (Explain recursive search & AI confidence)
4. **Verified Identity Assets** (Table of profiles)
5. **Risk & Threat Assessment** (Analyze breaches and scoring)
6. **Digital Forensics Analysis** (If image data was present)
7. **Sworn Conclusion** (Professional assessment)

Format the entire output in clean Markdown.`;

  const completion = await zai.chat.completions.create({
    messages: [
      { role: 'system', content: 'You are an expert investigative reporter. Use professional, objective language.' },
      { role: 'user', content: prompt }
    ],
    temperature: 0.3,
  });

  const reportContent = completion.choices[0]?.message?.content || 'Failed to generate brief.';

  return NextResponse.json({
    success: true,
    reportContent,
    format: 'markdown',
    filename
  });
}
